---
- name: install required kubespray deps
  become: yes
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - python-netaddr

- name: Disable swap
  command: swapoff -a

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- include: jinja.yml
